on:
  push:
    branches:
      - master

jobs:
  detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1
        with:
          included-paths: "web-server/,management-api/"
      
      - name: Print changed directories
        run: |
          echo "Changed directories are: ${{ steps.detect.outputs.changed }}"

  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest
    needs: detect-directory-changes
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: get-npm-version
        id: package-version
        run: |
          NODE_VERSION=$(node -p -e "require('./package.json').version")
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # The built in docker/build-push-action@v5 didn't work for another directory, so I had to use a custom step.
      - name: Print Docker registry path
        run: |
          echo "Docker registry path: $DOCKER_REGISTRY_PATH"
      - name: Build and push Docker image
        run: |
          echo "Building and pushing Docker image for ${{ matrix.project }}"
          DOCKER_REGISTRY_PATH=ghcr.io/${{ github.repository }}/${{ matrix.project }}:${{ steps.package-version.outputs.NODE_VERSION }}
          docker build -t $DOCKER_REGISTRY_PATH .
          docker push $DOCKER_REGISTRY_PATH
          echo "Docker image pushed to $DOCKER_REGISTRY_PATH"	