on:
  push:
    branches:
      - master

jobs:
  detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1
        with:
          included-paths: "./web-server/,./web-server/**,./management-api/,./management-api/**"
      
      - name: Print changed directories
        run: |
          echo "Changed directories are: ${{ steps.detect.outputs.changed }}"

  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest
    needs: detect-directory-changes
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}
    steps:
      - name: Get the project directory
        id: get-project-directory
        run: |
          PROJECT_DIRECTORY=$(echo ${{ matrix.project }} | cut -d '/' -f 1	)
          echo "PROJECT_DIRECTORY=${PROJECT_DIRECTORY}" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: get-npm-version
        id: package-version
        run: |
          NODE_VERSION=$(node -p -e "require('./${{ steps.get-project-directory.outputs.PROJECT_DIRECTORY }}/package.json').version")
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # The built in docker/build-push-action@v5 didn't work for another directory, so I had to use a custom step.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ steps.get-project-directory.outputs.PROJECT_DIRECTORY }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ steps.get-project-directory.outputs.PROJECT_DIRECTORY }}:${{ steps.package-version.outputs.NODE_VERSION }}